site_name: Kind Cluster Setup
site_description: A tool for setting up Kind clusters with independent app deployments
site_url: https://asb108.github.io/kind-cluster-setup
repo_url: https://github.com/asb108/kind-cluster-setup
repo_name: asb108/kind-cluster-setup

theme:
  name: material
  palette:
    primary: blue
    accent: blue

nav:
  - Home: README.md
  - Architecture: ARCHITECTURE.md
  - Contributing: CONTRIBUTING.md
  - Template Development: TEMPLATE_DEVELOPMENT_GUIDE.md
  - Documentation:
    - Core Abstractions: docs/core_abstractions.md
    - Application Management: docs/application_management.md
    - Deployment Guide: docs/deployment.md
    - UI Guide: docs/ui-guide.md

plugins:
  - search

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
