apiVersion: v1
kind: Service
metadata:
  name: airflow-webserver
  labels:
    app: airflow
    component: webserver
spec:
  type: NodePort
  ports:
  - name: web
    port: 8080
    targetPort: 8080
    nodePort: 30081
  selector:
    app: airflow
    component: webserver
