apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-postgres
  labels:
    app: airflow-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow-postgres
  template:
    metadata:
      labels:
        app: airflow-postgres
    spec:
      containers:
      - name: postgres
        image: postgres:14
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: postgres
        - name: POSTGRES_DB
          value: airflow
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
          requests:
            cpu: "500m"
            memory: "512Mi"
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: airflow-postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: airflow-postgres
  labels:
    app: airflow-postgres
spec:
  ports:
  - port: 5432
    targetPort: 5432
  selector:
    app: airflow-postgres
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflow-postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi