apiVersion: v1
kind: Service
metadata:
  name: airflow-webserver
  labels:
    app: airflow
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    nodePort: 30080
  selector:
    app: airflow
    component: webserver